<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Articles 184-565 of the Somali Penal Code, used to populate the
     * Article registry for selection in case legal-provision fields.
     */
    private array $articles = [
            [184, 'Attempts against the Integrity, Independence, or Unity of the Somali State'],
            [185, 'Citizen Who Bears Arms against the Somali State'],
            [186, 'Intelligence with Foreigners for the Purpose of Waging War against the Somali State'],
            [187, 'Hostile Acts against a Foreign State Which Expose the Somali State to the Danger of War'],
            [188, 'Intelligence with Foreigners for the Purpose of Engaging the Somali State to Neutrality or War'],
            [189, 'Corruption of a Citizen by Foreigners'],
            [190, 'Favoring the Enemy in Time of War'],
            [191, 'Providing the Enemy with Supplies'],
            [192, 'Participation in Loans in Favor of the Enemy'],
            [193, 'Trading with the Enemy'],
            [194, 'Failure to Execute Contracts for Supplies in Time of War'],
            [195, 'Fraud in Furnishing Supplies in Time of War'],
            [196, 'Destruction or Sabotage of Military Works'],
            [197, 'Facilitation with Culpa'],
            [198, 'Suppression, Falsification, or Purloining of Papers or Documents Concerning the Somali State'],
            [199, 'Procuring Information Regarding the Security of the Somali State'],
            [200, 'Political or Military Espionage'],
            [201, 'Espionage Concerning Information, the Disclosure of Which Has Been Prohibited'],
            [202, 'Facilitation with Culpa'],
            [203, 'Clandestine Penetration into Military Areas and Unjustified Possession of Means of Espionage'],
            [204, 'Disclosure of State Secrets'],
            [205, 'Disclosure of Information Which Has Been Prohibited'],
            [206, 'Utilization of State Secrets'],
            [207, 'Unfaithfulness in Handling State Matters'],
            [208, 'Political Defeatism'],
            [209, 'Instigating Soldiers to Disobey the Law'],
            [210, 'Economic Defeatism'],
            [211, 'Offenses against Allied States'],
            [212, 'Anti-National Activity of a Citizen Abroad'],
            [213, 'Subversive Associations'],
            [214, 'Anti-National Associations'],
            [215, 'Subversive or Anti-National Propaganda'],
            [216, 'Acceptance of Honors or Benefits from an Enemy State'],
            [217, 'Attempts against the Order Established by the Constitution'],
            [218, 'Attempts against the Constitutional Organs'],
            [219, 'Bringing the Nation or the State into Contempt'],
            [220, 'Offending the Honor or Prestige of the Head of the State'],
            [221, 'Armed Insurrection against the Powers of the State'],
            [222, 'Devastation, Pillage, and Slaughter'],
            [223, 'Civil War'],
            [224, 'Usurpation of Political Powers or Military Command'],
            [225, 'Unauthorized Enlistment or Arming in the Service of a Foreign State'],
            [226, 'Attempts against the Political Rights of a Citizen'],
            [227, 'Attempts against the Heads or Representatives of Foreign States'],
            [228, 'Bringing into Contempt the Flag or Emblem of a Foreign State'],
            [229, 'Condition of Reciprocity'],
            [230, 'Instigation to Commit Any of the Crimes Referred to in Chapters I and II'],
            [231, 'Public Instigation and Extolling Crimes'],
            [232, 'Political Conspiracy by Agreement'],
            [233, 'Political Conspiracy by Association'],
            [234, 'Formation of and Participating in Armed Groups'],
            [235, 'Conspiracy: Exemption from Punishment'],
            [236, 'Armed Groups: Exemption from Punishment'],
            [237, 'Time of War'],
            [238, 'Extenuating Circumstances: Acts of Slight Importance'],
            [239, 'Expulsion of Foreigners'],
            [240, 'Definition'],
            [241, 'Peculation'],
            [242, 'Misappropriation to the Prejudice of Private Persons'],
            [243, 'Peculation by Taking Advantage of the Error of Another Person'],
            [244, 'Extortion by a Public Officer'],
            [245, 'Corruption for Performing an Official Act'],
            [246, 'Corruption for Performing an Act Contrary to the Duties of Office'],
            [247, 'Corruption of a Person Entrusted with a Public Service'],
            [248, 'Punishment of Persons Giving or Promising Money or Other Benefit'],
            [249, 'Instigation of Corruption'],
            [250, 'Abuse of Office in Cases Not Specifically Provided for by Law'],
            [251, 'Private Interest in Official Acts'],
            [252, 'Utilization of Inventions or Discoveries by Reason of Office'],
            [253, 'Disclosure of Official Secrets'],
            [254, 'Incitement to Disparage or Bring into Contempt Public Institutions, Laws, or Orders of Authorities'],
            [255, 'Omission or Refusal to Perform Official Acts'],
            [256, 'Collective Abandonment of Public Offices, Employments, Services, or Works'],
            [257, 'Interruption of a Public Service or a Service of Public Necessity'],
            [258, 'Failure to Perform Duties of Office on the Occasion of Abandonment of a Public Office or of Interruption of a Public Service'],
            [259, 'Individual Abandonment of Public Office, Service, or Work'],
            [260, 'Cases Not Punishable'],
            [261, 'Removal or Damage of Property Subjected to Attachment or Sequestration'],
            [262, 'Violation with Culpa of the Duties Inherent in the Custody of Property Attached or Sequestrated'],
            [263, 'Force or Threats to a Public Officer'],
            [264, 'Resistance to a Public Officer'],
            [265, 'Force or Threats to a Political, Administrative, or Judicial Body'],
            [266, 'Aggravating Circumstances'],
            [267, 'Interruption of a Public Office or Service or a Service of Public Necessity'],
            [268, 'Insult to a Public Officer'],
            [269, 'Insult to a Political, Administrative, or Judicial Body'],
            [270, 'Insult to a Judge during a Hearing'],
            [271, 'Offense against the Authorities by Means of Damaging Posters'],
            [272, 'Pretending to Have Influence with a Public Officer'],
            [273, 'Usurpation of Public Functions'],
            [274, 'Abusive Exercise of a Profession'],
            [275, 'Tampering with Seals'],
            [276, 'Facilitation with Culpa'],
            [277, 'Violation of the Public Custody of Articles'],
            [278, 'Sale of Printed Matter the Sequestration of Which Has Been Ordered'],
            [279, 'Interfering with Auctions'],
            [280, 'Breach of Contracts for Public Supplies'],
            [281, 'Fraud in Public Supplies'],
            [282, 'Omission or Delay on the Part of a Public Officer or a Person Entrusted with a Public Service to Give Information of an Offense'],
            [283, 'Omission by a Citizen to Give Information Regarding an Offense'],
            [284, 'Omission to Report by a Member of the Medical Profession'],
            [285, 'Refusal of Services Legally Due'],
            [286, 'Simulation of Offense'],
            [287, 'False Accusation'],
            [288, 'False Self-Accusation'],
            [289, 'Simulation or False Accusation for an Act Constituting a Contravention'],
            [290, 'Perjury by a Party to a Suit'],
            [291, 'False Evidence'],
            [292, 'False Opinion of Experts or False Interpretation'],
            [293, 'Fraud in Proceedings'],
            [294, 'Aggravating Circumstances'],
            [295, 'Retraction'],
            [296, 'Subornation'],
            [297, 'Assistance to a Suspected Person'],
            [298, 'Assistance Relating to the Object of a Crime'],
            [299, 'Unfaithful Advocates or Technical Advisers'],
            [300, 'Other Acts of Betrayal of Trust by Advocates and Technical Advisers'],
            [301, 'Advocate Pretending to Have Influence'],
            [302, 'Interdiction from Public Offices'],
            [303, 'Cases Which Are Not Punishable'],
            [304, 'Definition of Near Relative'],
            [305, 'Escape'],
            [306, 'Assisting Escape'],
            [307, 'Custodian Acting with Culpa'],
            [308, 'Willful Disobedience to Execute an Order of the Judge'],
            [309, 'Non-Observance of Accessory Penalties'],
            [310, 'Facilitating Non-Observance of Punishment'],
            [311, 'Facilitating Non-Observance of Measures of Detentive Security'],
            [312, 'Unauthorized Exercise of Private Rights'],
            [313, 'Bringing the Religion of the State into Contempt'],
            [314, 'Disturbance of Religious Functions'],
            [315, 'Crimes against Forms of Worship Permitted in the State'],
            [316, 'Violation of or Bringing Contempt upon Tombs or Disturbance of Funerals or Funeral Services'],
            [317, 'Bringing into Contempt Dead Bodies'],
            [318, 'Destruction, Concealment, or Removal of Dead Bodies'],
            [319, 'Unlawful Use of Dead Bodies'],
            [320, 'Instigation to Delinquency'],
            [321, 'Instigation to Disobey the Laws'],
            [322, 'Association for Purpose of Committing Crimes'],
            [323, 'Security Measures'],
            [324, 'Devastation and Pillage'],
            [325, 'Intimidation of the Public by Means of Explosive Materials'],
            [326, 'Intimidation of the Public'],
            [327, 'Giving False Alarm to Authorities'],
            [328, 'Publication or Circulation of False, Exaggerated, or Tendentious News Capable of Disturbing Public Order'],
            [329, 'Carnage'],
            [330, 'Causing Disaster'],
            [331, 'Unlawful Omission to Take or Removal of Precautions against Accidents'],
            [332, 'Attempts Endangering Public Safety'],
            [333, 'Causing Impediments to Protection of Public Safety'],
            [334, 'Epidemics'],
            [335, 'Pollution of Water and Food'],
            [336, 'Adulteration and Simulation of Food'],
            [337, 'Adulteration or Simulation of Other Articles to the Detriment of Public Health'],
            [338, 'Sale of Adulterated or Simulated Food'],
            [339, 'Sale of Noxious Food'],
            [340, 'Sale and Supply of Spoiled Medicinal Substances'],
            [341, 'Supply of Medicinal Substances in a Manner Dangerous to Public Health'],
            [342, 'Trading in Narcotics'],
            [343, 'Abetting of the Use of Narcotics'],
            [344, 'Crimes with Culpa Involving Damage'],
            [345, 'Crimes with Culpa Involving Danger'],
            [346, 'Culpable Omission of Precautions or Protections against Disasters or Accidents'],
            [347, 'Crimes with Culpa against Public Health'],
            [348, 'Counterfeiting Currency, Spending or Introducing into the State Counterfeit Currency by Concerted Action'],
            [349, 'Spending or Introducing Counterfeit Currency into the State, without Concerted Action'],
            [350, 'Spending Counterfeit Currency Received in Good Faith'],
            [351, 'Equivalence of Securities to Currency'],
            [352, 'Counterfeiting of Stamps and Introduction into the State, Purchase, Possession, or Placing in Circulation of Counterfeit Stamps'],
            [353, 'Counterfeiting of Watermarked Paper Used for the Manufacture of Securities or Stamps'],
            [354, 'Manufacturing or Possessing of Watermarks or Instruments Intended for Counterfeiting Currency, Stamps, or Watermarked Paper'],
            [355, 'Counterfeiting of Tickets of Public Transport'],
            [356, 'Exemption Punishment'],
            [357, 'Use of Counterfeit or Altered Stamps'],
            [358, 'Use of Counterfeit Tickets of Public Transport'],
            [359, 'Alteration of Marks on Used Stamps or Tickets and Use of Articles Thus Altered'],
            [360, 'Counterfeiting the Seal of the State, and Use of the Counterfeit Seal'],
            [361, 'Counterfeiting of Other Public Seals or Instruments Intended for Public Authentication or Certification, and Use of Such Counterfeit Seals and Instruments'],
            [362, 'Counterfeiting the Impressions of a Public Authentication or Certification'],
            [363, 'Improper Use of Genuine Instruments'],
            [364, 'Use or Possession of Measures or Weights with False Stamp'],
            [365, 'Counterfeiting, Alteration, or Use of Identification Marks of Literary or Artistic Works, or Industrial Products'],
            [366, 'Falsification of Public Documents by a Public Officer'],
            [367, 'Falsification of Administrative Certificates or Authorizations by a Public Officer'],
            [368, 'Falsification of Authentic Copies of Public or Private Documents and of Certificates of the Contents of Documents by a Public Officer'],
            [369, 'False Certification of Public Documents by a Public Officer'],
            [370, 'False Certification of Administrative Certificates or Authorizations by a Public Officer'],
            [371, 'False Certification by a Person Performing a Service of Public Necessity'],
            [372, 'False Certification by a Private Individual'],
            [373, 'False Certification of a Public Document by a Private Individual'],
            [374, 'Falsification of Registers and Notifications'],
            [375, 'Falsification of Private Deed'],
            [376, 'Falsification of Paper Signed in Blank: Private Document'],
            [377, 'Falsification of Paper Signed in Blank: Public Document'],
            [378, 'Use of False Document'],
            [379, 'Suppression, Destruction, or Concealment of Genuine Documents'],
            [380, 'Documents Deemed Equivalent to Public Documents for the Purposes of Punishment'],
            [381, 'Authentic Copies of Missing Originals'],
            [382, 'Falsification Committed by Persons Entrusted with a Public Service'],
            [383, 'Substitution of Person'],
            [384, 'False Certification or Declaration to a Public Officer'],
            [385, 'False Statements as to Identity or Personal Capacity'],
            [386, 'Usurpation of Titles or Honors'],
            [387, 'Destruction of Raw Materials or Agricultural or Industrial Products or Means of Production'],
            [388, 'Diffusion of Diseases of Plants or Animals'],
            [389, 'Fraudulent Raising or Lowering of Prices in the Public Market'],
            [390, 'Lockouts and Strikes'],
            [391, 'Unauthorized Occupation of Agricultural or Industrial Undertakings and Sabotage'],
            [392, 'Accessory Penalty'],
            [393, 'Infringement of Freedom of Industry and Commerce'],
            [394, 'Fraud against National Industries'],
            [395, 'Fraud in the Exercise of Commerce'],
            [396, 'Sale of Non-Genuine Food Products as Genuine'],
            [397, 'Sale of Industrial Products under False Signs'],
            [398, 'Carnal Violence'],
            [399, 'Acts of Lust Committed with Violence'],
            [400, 'Unnatural Offenses Committed with Violence'],
            [401, 'Abduction for Purposes of Lust or Marriage'],
            [402, 'Obscene Acts'],
            [403, 'Obscene Publications and Performances'],
            [404, 'Definition of Obscene Acts and Objects'],
            [405, 'Prostitution'],
            [406, 'Incitement to Lewd Acts'],
            [407, 'Instigation, Aiding, and Exploitation of Prostitution'],
            [408, 'Compulsion to Prostitution'],
            [409, 'Homosexuality'],
            [410, 'Security Measures'],
            [411, 'Supply or Sale of Alcoholic Beverages'],
            [412, 'Consumption of Alcoholic Beverages'],
            [413, 'Drunkenness'],
            [414, 'Causing a State of Drunkenness in Other Persons'],
            [415, 'Supply of Alcoholic Beverages to a Person in a State of Manifest Drunkenness'],
            [416, 'Unlawful Manufacture of or Trade in Liquors or Substances Intended for the Preparation of Same'],
            [417, 'Definition'],
            [418, 'Abortion without Consent'],
            [419, 'Abortion with Consent'],
            [420, 'Instigation to Abortion'],
            [421, 'Death or Injury of the Woman'],
            [422, 'Abortion for Reasons of Honor'],
            [423, 'Procuring the Impotence of a Person to Procreate'],
            [424, 'Aggravating Circumstances and Accessory Penalty'],
            [425, 'Illegal Marriage'],
            [426, 'Adultery'],
            [427, 'Incest'],
            [428, 'Simulation or Suppression of Entries in Civil Register'],
            [429, 'Alteration of Entries in Civil Register'],
            [430, 'Violation of Duty toward Family'],
            [431, 'Abuse of Measures of Correction Discipline'],
            [432, 'Ill-Treatment of Children and Members of the Family'],
            [433, 'Abduction of Persons under Legal Incapacity'],
            [434, 'Murder'],
            [435, 'Infanticide for Reason of Honor'],
            [436, 'Death Caused to a Person with His Own Consent'],
            [437, 'Attempt to Commit Suicide'],
            [438, 'Instigating or Aiding to Commit Suicide'],
            [439, 'Assault'],
            [440, 'Hurt'],
            [441, 'Homicide without the Intention of Causing Death'],
            [442, 'Homicide or Hurt Caused by Parent'],
            [443, 'Homicide and Hurt for Reasons of Honor'],
            [444, 'Affray'],
            [445, 'Death Caused by Negligence'],
            [446, 'Hurt Caused by Negligence'],
            [447, 'Death or Hurt Caused as a Consequence of Another Crime'],
            [448, 'Abandonment of Minors or Incapable Persons'],
            [449, 'Abandonment of a Newly Born Child for Reasons of Honor'],
            [450, 'Failure to Render Assistance'],
            [451, 'Insult'],
            [452, 'Defamation'],
            [453, 'Proof of Truth'],
            [454, 'Provocation'],
            [455, 'Reduction to Slavery'],
            [456, 'Dealing and Trading in Slaves'],
            [457, 'Sale and Purchase of Slaves'],
            [458, 'Enforced Subjection'],
            [459, 'Crimes Committed Abroad'],
            [460, 'Seizure of a Person'],
            [461, 'Illegal Arrest'],
            [462, 'Abuse of Authority toward a Person Arrested or Detained'],
            [463, 'Arbitrary Personal Search and Inspection'],
            [464, 'Compulsory Labor'],
            [465, 'Violation of the Right to Engage Workers or to Participate in a Trade Union'],
            [466, 'Private Violence'],
            [467, 'Violence or Threats Used to Cause the Commission of an Offense'],
            [468, 'Threats'],
            [469, 'State of Incapacity Produced through Violence'],
            [470, 'Violation of the Privacy of the Home'],
            [471, 'Violation of the Privacy of the Home Committed by a Public Officer'],
            [472, 'Interception, Removal, and Suppression of Correspondence'],
            [473, 'Fraudulent Ascertainment, Interruption, and Prevention of Telegraphic or Telephonic Communications or Conversations'],
            [474, 'Disclosing the Contents of Correspondence'],
            [475, 'Interception, Removal, and Suppression of Correspondence Committed by a Person Employed in the Postal, Telegraph, or Telephone Services'],
            [476, 'Disclosure of Contents of Correspondence by a Person Employed in the Postal, Telegraph, or Telephone Services'],
            [477, 'Disclosing the Contents of Secret Documents'],
            [478, 'Disclosing Professional Secrets'],
            [479, 'Disclosing Scientific or Industrial Secrets'],
            [480, 'Theft'],
            [481, 'Aggravating Circumstances'],
            [482, 'Thefts Punishable on the Complaint of the Party Injured'],
            [483, 'Taking Movable Property in Joint Ownership'],
            [484, 'Robbery'],
            [485, 'Extortion'],
            [486, 'Detention of a Person for the Purpose of Robbery or Extortion'],
            [487, 'Trespass'],
            [488, 'Deflection of Waters and Alteration of Place Features'],
            [489, 'Trespass on Lands or Buildings'],
            [490, 'Violent Disturbance of the Possession of Immovable Property'],
            [491, 'Damage to Property'],
            [492, 'Trespass by Animals'],
            [493, 'Wrongful Entry upon Enclosed Property'],
            [494, 'Killing or Injuring of Animals'],
            [495, 'Disfigurement and Contamination of Property'],
            [496, 'Cheating'],
            [497, 'Fraudulent Insolvency'],
            [498, 'Issuing Checks Which Will Not Be Honored'],
            [499, 'Fraudulent Destruction of One\'s Own Property and Fraudulent Self-Mutilation'],
            [500, 'Undue Influence on Persons under Disability'],
            [501, 'Usury'],
            [502, 'Misappropriation'],
            [503, 'Misappropriation of Articles Lost, Treasure Trove, or Articles Obtained through Error or Chance'],
            [504, 'Receiving'],
            [505, 'Non-Observance of Orders of the Authorities'],
            [506, 'Refusal to Give Particulars Regarding One\'s Personal Identity'],
            [507, 'Refusal to Lend Assistance on the Occasion of a Riot'],
            [508, 'Formation of Armed Bodies Not Intended for the Commission of Offenses'],
            [509, 'Seditious Cries and Manifestations'],
            [510, 'Seditious Assembly'],
            [511, 'Cries or News Capable of Disturbing Public or Private Tranquility'],
            [512, 'Disturbing the Occupations or the Repose of Individuals'],
            [513, 'Molestation or Disturbance of Individuals'],
            [514, 'Abusing the Credulity of the Public'],
            [515, 'Wrongful Exercise of the Typographic Art'],
            [516, 'Wrongful Sale, Distribution, or Posting of Papers or Drawing'],
            [517, 'Destruction or Defacement of Posters'],
            [518, 'Unauthorized or Prohibited Business Agencies and Public Trading Concerns'],
            [519, 'Public Performances or Entertainments without License'],
            [520, 'Wrongful Performance of Acts Intended for Reproduction by the Cinematograph'],
            [521, 'Wrongful Theatrical or Cinematographic Performances'],
            [522, 'Wrongful Exercise of Itinerant Callings'],
            [523, 'Begging'],
            [524, 'Failure to Exercise Custody and Detentive Control of Animals'],
            [525, 'Failure to Place or Removal of Signals or Means of Protection'],
            [526, 'Dangerous Throwing of Articles'],
            [527, 'Dangerous Placing of Articles'],
            [528, 'Collapse of Buildings or Other Constructions'],
            [529, 'Failure to Perform Work on Buildings or Constructions Which Threaten to Collapse'],
            [530, 'Unlawful Manufacture of and Trade in Explosive Materials'],
            [531, 'Failure to Declare Explosive Materials'],
            [532, 'Aggravating Circumstances'],
            [533, 'Unlawful Opening of Places of Public Show or Entertainment'],
            [534, 'Unauthorized Entry into Places Where Admittance Is Forbidden in the Military Interest of the State'],
            [535, 'Holding of Illegal Measures or Weights'],
            [536, 'Refusal of Coins Which Are Legal Tender'],
            [537, 'Failure to Deliver Up Coins Recognized as Counterfeit'],
            [538, 'Unauthorized Publication of Documents or Information Relating to Criminal Proceedings'],
            [539, 'Failure to Keep Arms in Custody'],
            [540, 'Dangerous Ignitions and Explosions'],
            [541, 'Arms'],
            [542, 'Unjustified Possession of Altered Keys or Pick-Locks'],
            [543, 'Unjustified Possession of Valuables'],
            [544, 'Unjustified Possession of Animals'],
            [545, 'Failure to Declare Articles Which Are Stolen Property'],
            [546, 'Sale or Delivery of Keys or Pick-Lock to an Unknown Person'],
            [547, 'Unauthorized Opening of Places or Objects'],
            [548, 'Purchase of Articles Suspected to Be Stolen Property'],
            [549, 'Failure to Retain in Custody or Unauthorized Custody of Persons of Unsound Mind or Minors in Asylums or Reformatories'],
            [550, 'Failure to Retain in Private Custody or Unauthorized Private Custody of Persons of Unsound Mind'],
            [551, 'Failure to Notify the Authorities of the Escape or Flight of Persons of Unsound Mind or Minors'],
            [552, 'Failure to Declare Dangerous Mental Infirmities'],
            [553, 'Conduct of Games of Chance'],
            [554, 'Aggravating Circumstances'],
            [555, 'Participation in Games of Chance'],
            [556, 'Essential Elements of a Game of Chance; Gaming House'],
            [557, 'Confiscation'],
            [558, 'Unlawful Holding of Games Not of Chance'],
            [559, 'Blasphemy and Offensive Acts toward the Dead'],
            [560, 'Trade in Writings, Drawing, or Other Articles Contrary to Public Decency'],
            [561, 'Acts Contrary to Public Decency; Foul Language'],
            [562, 'Cruelty to Animals'],
            [563, 'Treatment Capable of Depriving Another of Consciousness or Will'],
            [564, 'Abuse of Stupefying Substances'],
            [565, 'Supply of Poisonous or Harmful Substances to Minors'],
    ];

    public function up(): void
    {
        $now = now();

        DB::table("articles")->insertOrIgnore(
            array_map(fn ($row) => [
                "article_number" => $row[0],
                "title"          => $row[1],
                "created_at"     => $now,
                "updated_at"     => $now,
            ], $this->articles)
        );
    }

    public function down(): void
    {
        $numbers = array_column($this->articles, 0);
        DB::table("articles")->whereIn("article_number", $numbers)->delete();
    }
};
